// @flow
export const UNITS: string = 'UNITS'
export const ZERG: string = 'ZERG'
export const DATA: string = 'DATA'
export const PARAMS: string = 'PARAMS'
export const ID: string = 'ID'
export const NAME: string = 'NAME'
export const POSITION: string = 'POSITION'
export const TYPE: string = 'TYPE'
export const ROLE: string = 'ROLE'
export const MAX_HEALTH: string = 'MAX_HEALTH'
export const HEALTH: string = 'HEALTH'
export const SIZE: string = 'SIZE'
export const SPEED: string = 'SPEED'